title: John Doe # your name (or website title) here
logo: "conrad-cruz.github.io/conradcruzpfp.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  QC Validation Analyst Learning Data Science and Bioinformatics
  <br><br>
  Various Projects from School or Freetime Posted here.
  <br><br>
  <a href="https://www.linkedin.com/in/conrad-cruz-17b578171/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
